<?php

/**
  * @file
  * Allows visitors to calculate price difference of trip.
  */

/**
 * Implements hook_menu().
 */
function calculator_menu() {
  $items = array();

  $items['airport/calculator'] = array(
    'title' => 'Trip Calculator',
    'description' => 'Configure calculation information for trip calculator.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('calculator_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_form().
 */
 function calculator_form($form, &$form_submit) {
  $form = array();
  $totalcos = '';
  $totalden = '';
  
  /*
  $form['overview'] = array (
	'#markup' => t('This is just a test.'),
	'#prefix' => '<p>',
	'#suffix' => '</p>',
  );
  */
  $form['cos'] = array (
	'#title' => t('Colorado Springs Airport'),
	'#type' => 'fieldset',
	'#prefix' => '<div style="max-width:40%;float:left;">',
	'#suffix' => '</div>',
	'#collapsible' => false,
	'#collapsed' => false,
  );
  
  // BEGIN COLORADO SPRINGS COSTS
  $form['cos']['calculator_flight_cost_cos'] = array(
    '#title' => t('Flight Cost'),
    '#description' => t('The amount you pay for your ticket to fly from the Colorado Springs airport.'),
    '#type' => 'textfield',
    '#maxlength' => 11,
	'#size' => 20, 
    '#default_value' => variable_get('calculator_flight_cost_cos'),
    '#weight' => 1,
  );
  
  $form['cos']['calculator_parking_rate_cos'] = array(
    '#title' => t('Parking Rate'),
    '#description' => t('The amount you pay to leave your car at the Colorado Springs airport.'),
    '#type' => 'select',
	'#options' => array(
		'6' => t('Long Term $6'), 
		'8' => t('Short Term $8'), 
		'14' => t('Valet $14'),
	),
	'#field_suffix' => t('Per Day'),
    '#validated' => true,
    '#weight' => 2,
  );
  
  $form['cos']['calculator_free_parking_cos'] = array(
    '#title' => t('Free parking (coupon)'),
    '#description' => t(''),
    '#type' => 'select',
	'#options' => drupal_map_assoc(
		array(
			'2' => t('2 coupons'),
			'1' => t('1 coupon'),
			'0' => t('No coupons')
		)
	),
	'#validated' => true,
    '#weight' => 3,
  );
  
  $form['cos']['calculator_days_travel_cos'] = array(
    '#title' => t('Days of travel'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variable_get('calculator_days_travel_cos'),
	'#size' => 20, 
    '#weight' => 4,
  );
  
  $form['cos']['calculator_mileage_charge_cos'] = array(
    '#title' => t('Mileage charge'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variable_get('calculator_mileage_charge_cos'),
	'#size' => 20, 
    '#weight' => 5,
  );
  
  $form['cos']['calculator_distance_miles_cos'] = array(
    '#title' => t('Distance to Airport (miles)'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variable_get('calculator_distance_miles_cos'),
	'#size' => 20, 
    '#weight' => 6,
  );
  
  $form['cos']['calculator_toll_cos'] = array(
    '#title' => t('Toll: E470'),
    '#description' => t(''),
    '#type' => 'checkbox',
    '#default_value' => variable_get('calculator_toll_cos'),
    '#weight' => 7,
	'#disabled' => true,
  );
  
  $form['cos']['calculator_cab_fare_cos'] = array(
    '#title' => t('Cab or shuttle fare'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variable_get('calculator_cab_fare_cos'),
	'#size' => 20, 
    '#weight' => 8,
  );
  
  $form['cos']['calculator_hourly_rate_cos'] = array(
    '#title' => t('Hourly rate'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variable_get('calculator_hourly_rate_cos'),
	'#size' => 20, 
    '#weight' => 9,
  );
  
  $form['cos']['calculator_driving_time_cos'] = array(
    '#title' => t('Driving time (minutes)'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variable_get('calculator_driving_time_cos'),
	'#size' => 20, 
    '#weight' => 10,
  );
  
  /*
  $form['den'] = array (
	'#title' => t('Denver International Airport'),
	'#type' => 'fieldset',
	'#prefix' => '<div style="max-width:40%;float:left;">',
	'#suffix' => '</div>',
	'#collapsible' => false,
	'#collapsed' => false,
  );
  
  // BEGIN DENVER COSTS
  $form['den']['calculator_flight_cost_den'] = array(
    '#title' => t('Flight Cost'),
    '#description' => t('The amount you pay for your ticket to fly from the Denver airport.'),
    '#type' => 'textfield',
	'#maxlength' => 11,
	'#maxlength' => 11,
    '#default_value' => t('$0.00'),
	'#size' => 20, 
    '#weight' => 1,
  );
  
  $form['den']['calculator_parking_rate_den'] = array(
    '#title' => t('Parking Rate (per day)'),
    '#description' => t('The amount you pay to leave your car at the Denver airport.'),
    '#type' => 'select',
	'#options' => drupal_map_assoc(
		array(
			t('Shuttle Lot $8'), 
			t('Economy $12'), 
			t('Garage $23'), 
			t('Valet $32'), 
			t('Short Term $96')
		)
	),
	'#validated' => true,
    '#weight' => 2,
  );
  
  $form['den']['calculator_free_parking_den'] = array(
    '#title' => t('Free parking (coupon)'),
    '#description' => t(''),
    '#type' => 'select',
	'#options' => drupal_map_assoc(array(t('N/A'))),
    '#default_value' => null,
	'#disabled' => true,
    '#weight' => 3,
  );
  
  $form['den']['calculator_days_travel_den'] = array(
    '#title' => t('Days of travel'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => null,
	'#size' => 20, 
    '#weight' => 4,
  );
  
  $form['den']['calculator_mileage_charge_den'] = array(
    '#title' => t('Mileage charge'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => t('0.565'),
	'#size' => 20, 
    '#weight' => 5,
  );
  
  $form['den']['calculator_distance_miles_den'] = array(
    '#title' => t('Distance to Airport (miles)'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => null,
	'#size' => 20, 
    '#weight' => 6,
  );
  
  $form['den']['calculator_toll_den'] = array(
    '#title' => t('Toll: E470'),
    '#description' => t(''),
    '#type' => 'checkbox',
    '#default_value' => false,
    '#weight' => 7,
  );
  
  $form['den']['calculator_cab_fare_den'] = array(
    '#title' => t('Cab or shuttle fare'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => t('$0.00'),
	'#size' => 20, 
    '#weight' => 8,
  );
  
  $form['den']['calculator_hourly_rate_den'] = array(
    '#title' => t('Hourly rate'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => null,
	'#size' => 20, 
    '#weight' => 9,
  );
  
  $form['den']['calculator_driving_time_den'] = array(
    '#title' => t('Driving time (minutes)'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variabel_set('calculator_driving_time_den'),
	'#size' => 20, 
    '#weight' => 10,
  );
  */
  
  // Do some math?
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Calculate'),
	'#prefix' => '<div style="clear:both;">',
	'#suffix' => '</div>',
  );
  
  return $form;
}

/**
 * Implements hook_form_submit().
 */
function calculator_form_submit($form, &$form_state) {
	// Rebuild the form.
	$form_state['rebuild'] = TRUE;
	dpm($form);
	
	// Arrange results.
}

  